require("fastbyte.options")
require("fastbyte.lazy")
require("fastbyte.builtin-plugins")
require("fastbyte.keymaps")
-- require("fastbyte.highlight_yank")
-- require("fastbyte.rotate_windows")
-- require("fastbyte.vertical_help")
-- require("fastbyte.toggle_diagnostics")
-- require("fastbyte.copy_file_path_to_clipboard")
-- require("fastbyte.ocaml_extensions")
-- require("fastbyte.set_column_width")
require("fastbyte.autocmds")

vim.cmd.colorscheme("catppuccin-mocha")
